export const FETCH_MUSIC_REQUEST = "FETCH_MUSIC_REQUEST";
export const FETCH_MUSIC_SUCCESS = "FETCH_MUSIC_SUCCESS";
export const FETCH_MUSIC_FAILURE = "FETCH_MUSIC_FAILURE";
export const UPDATE_MUSIC_LIST = "UPDATE_MUSIC_LIST";
export const SELECT_MUSIC = "SELECT_MUSIC";
export const GET_DURATIONPLAYED = "GET_DURATIONPLAYED";
